/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zabeer.kafkastreaming.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ItemProcessed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 426734276161395341L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemProcessed\",\"namespace\":\"com.zabeer.kafkastreaming.model\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"itemTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"price\",\"type\":\"float\"},{\"name\":\"sequence\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemProcessed> ENCODER =
      new BinaryMessageEncoder<ItemProcessed>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemProcessed> DECODER =
      new BinaryMessageDecoder<ItemProcessed>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ItemProcessed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ItemProcessed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ItemProcessed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ItemProcessed>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ItemProcessed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ItemProcessed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ItemProcessed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ItemProcessed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence code;
   private java.lang.CharSequence description;
   private long itemTimestamp;
   private float price;
   private java.lang.Long sequence;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemProcessed() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param code The new value for code
   * @param description The new value for description
   * @param itemTimestamp The new value for itemTimestamp
   * @param price The new value for price
   * @param sequence The new value for sequence
   */
  public ItemProcessed(java.lang.CharSequence id, java.lang.CharSequence code, java.lang.CharSequence description, java.lang.Long itemTimestamp, java.lang.Float price, java.lang.Long sequence) {
    this.id = id;
    this.code = code;
    this.description = description;
    this.itemTimestamp = itemTimestamp;
    this.price = price;
    this.sequence = sequence;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return code;
    case 2: return description;
    case 3: return itemTimestamp;
    case 4: return price;
    case 5: return sequence;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: code = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: itemTimestamp = (java.lang.Long)value$; break;
    case 4: price = (java.lang.Float)value$; break;
    case 5: sequence = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'itemTimestamp' field.
   * @return The value of the 'itemTimestamp' field.
   */
  public long getItemTimestamp() {
    return itemTimestamp;
  }


  /**
   * Sets the value of the 'itemTimestamp' field.
   * @param value the value to set.
   */
  public void setItemTimestamp(long value) {
    this.itemTimestamp = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public float getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(float value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'sequence' field.
   * @return The value of the 'sequence' field.
   */
  public java.lang.Long getSequence() {
    return sequence;
  }


  /**
   * Sets the value of the 'sequence' field.
   * @param value the value to set.
   */
  public void setSequence(java.lang.Long value) {
    this.sequence = value;
  }

  /**
   * Creates a new ItemProcessed RecordBuilder.
   * @return A new ItemProcessed RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemProcessed.Builder newBuilder() {
    return new com.zabeer.kafkastreaming.model.ItemProcessed.Builder();
  }

  /**
   * Creates a new ItemProcessed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemProcessed RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemProcessed.Builder newBuilder(com.zabeer.kafkastreaming.model.ItemProcessed.Builder other) {
    if (other == null) {
      return new com.zabeer.kafkastreaming.model.ItemProcessed.Builder();
    } else {
      return new com.zabeer.kafkastreaming.model.ItemProcessed.Builder(other);
    }
  }

  /**
   * Creates a new ItemProcessed RecordBuilder by copying an existing ItemProcessed instance.
   * @param other The existing instance to copy.
   * @return A new ItemProcessed RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemProcessed.Builder newBuilder(com.zabeer.kafkastreaming.model.ItemProcessed other) {
    if (other == null) {
      return new com.zabeer.kafkastreaming.model.ItemProcessed.Builder();
    } else {
      return new com.zabeer.kafkastreaming.model.ItemProcessed.Builder(other);
    }
  }

  /**
   * RecordBuilder for ItemProcessed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemProcessed>
    implements org.apache.avro.data.RecordBuilder<ItemProcessed> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence code;
    private java.lang.CharSequence description;
    private long itemTimestamp;
    private float price;
    private java.lang.Long sequence;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zabeer.kafkastreaming.model.ItemProcessed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.itemTimestamp)) {
        this.itemTimestamp = data().deepCopy(fields()[3].schema(), other.itemTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.sequence)) {
        this.sequence = data().deepCopy(fields()[5].schema(), other.sequence);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing ItemProcessed instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zabeer.kafkastreaming.model.ItemProcessed other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.itemTimestamp)) {
        this.itemTimestamp = data().deepCopy(fields()[3].schema(), other.itemTimestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.price)) {
        this.price = data().deepCopy(fields()[4].schema(), other.price);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sequence)) {
        this.sequence = data().deepCopy(fields()[5].schema(), other.sequence);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'itemTimestamp' field.
      * @return The value.
      */
    public long getItemTimestamp() {
      return itemTimestamp;
    }


    /**
      * Sets the value of the 'itemTimestamp' field.
      * @param value The value of 'itemTimestamp'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setItemTimestamp(long value) {
      validate(fields()[3], value);
      this.itemTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'itemTimestamp' field has been set.
      * @return True if the 'itemTimestamp' field has been set, false otherwise.
      */
    public boolean hasItemTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'itemTimestamp' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearItemTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public float getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setPrice(float value) {
      validate(fields()[4], value);
      this.price = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearPrice() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'sequence' field.
      * @return The value.
      */
    public java.lang.Long getSequence() {
      return sequence;
    }


    /**
      * Sets the value of the 'sequence' field.
      * @param value The value of 'sequence'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder setSequence(java.lang.Long value) {
      validate(fields()[5], value);
      this.sequence = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'sequence' field has been set.
      * @return True if the 'sequence' field has been set, false otherwise.
      */
    public boolean hasSequence() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'sequence' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemProcessed.Builder clearSequence() {
      sequence = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemProcessed build() {
      try {
        ItemProcessed record = new ItemProcessed();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.itemTimestamp = fieldSetFlags()[3] ? this.itemTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.price = fieldSetFlags()[4] ? this.price : (java.lang.Float) defaultValue(fields()[4]);
        record.sequence = fieldSetFlags()[5] ? this.sequence : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemProcessed>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemProcessed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemProcessed>
    READER$ = (org.apache.avro.io.DatumReader<ItemProcessed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.code);

    out.writeString(this.description);

    out.writeLong(this.itemTimestamp);

    out.writeFloat(this.price);

    if (this.sequence == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.sequence);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.itemTimestamp = in.readLong();

      this.price = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.sequence = null;
      } else {
        this.sequence = in.readLong();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.code = in.readString(this.code instanceof Utf8 ? (Utf8)this.code : null);
          break;

        case 2:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 3:
          this.itemTimestamp = in.readLong();
          break;

        case 4:
          this.price = in.readFloat();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sequence = null;
          } else {
            this.sequence = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










