/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zabeer.kafkastreaming.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ItemRetryTracker extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5364411700532930356L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemRetryTracker\",\"namespace\":\"com.zabeer.kafkastreaming.model\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"lastMessageSentForRetry\",\"type\":\"long\"},{\"name\":\"lastMessageProcessedOnRetry\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemRetryTracker> ENCODER =
      new BinaryMessageEncoder<ItemRetryTracker>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemRetryTracker> DECODER =
      new BinaryMessageDecoder<ItemRetryTracker>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ItemRetryTracker> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ItemRetryTracker> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ItemRetryTracker> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ItemRetryTracker>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ItemRetryTracker to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ItemRetryTracker from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ItemRetryTracker instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ItemRetryTracker fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private long lastMessageSentForRetry;
   private long lastMessageProcessedOnRetry;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemRetryTracker() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param lastMessageSentForRetry The new value for lastMessageSentForRetry
   * @param lastMessageProcessedOnRetry The new value for lastMessageProcessedOnRetry
   */
  public ItemRetryTracker(java.lang.CharSequence id, java.lang.Long lastMessageSentForRetry, java.lang.Long lastMessageProcessedOnRetry) {
    this.id = id;
    this.lastMessageSentForRetry = lastMessageSentForRetry;
    this.lastMessageProcessedOnRetry = lastMessageProcessedOnRetry;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return lastMessageSentForRetry;
    case 2: return lastMessageProcessedOnRetry;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: lastMessageSentForRetry = (java.lang.Long)value$; break;
    case 2: lastMessageProcessedOnRetry = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'lastMessageSentForRetry' field.
   * @return The value of the 'lastMessageSentForRetry' field.
   */
  public long getLastMessageSentForRetry() {
    return lastMessageSentForRetry;
  }


  /**
   * Sets the value of the 'lastMessageSentForRetry' field.
   * @param value the value to set.
   */
  public void setLastMessageSentForRetry(long value) {
    this.lastMessageSentForRetry = value;
  }

  /**
   * Gets the value of the 'lastMessageProcessedOnRetry' field.
   * @return The value of the 'lastMessageProcessedOnRetry' field.
   */
  public long getLastMessageProcessedOnRetry() {
    return lastMessageProcessedOnRetry;
  }


  /**
   * Sets the value of the 'lastMessageProcessedOnRetry' field.
   * @param value the value to set.
   */
  public void setLastMessageProcessedOnRetry(long value) {
    this.lastMessageProcessedOnRetry = value;
  }

  /**
   * Creates a new ItemRetryTracker RecordBuilder.
   * @return A new ItemRetryTracker RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder newBuilder() {
    return new com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder();
  }

  /**
   * Creates a new ItemRetryTracker RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemRetryTracker RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder newBuilder(com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder other) {
    if (other == null) {
      return new com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder();
    } else {
      return new com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder(other);
    }
  }

  /**
   * Creates a new ItemRetryTracker RecordBuilder by copying an existing ItemRetryTracker instance.
   * @param other The existing instance to copy.
   * @return A new ItemRetryTracker RecordBuilder
   */
  public static com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder newBuilder(com.zabeer.kafkastreaming.model.ItemRetryTracker other) {
    if (other == null) {
      return new com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder();
    } else {
      return new com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder(other);
    }
  }

  /**
   * RecordBuilder for ItemRetryTracker instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemRetryTracker>
    implements org.apache.avro.data.RecordBuilder<ItemRetryTracker> {

    private java.lang.CharSequence id;
    private long lastMessageSentForRetry;
    private long lastMessageProcessedOnRetry;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastMessageSentForRetry)) {
        this.lastMessageSentForRetry = data().deepCopy(fields()[1].schema(), other.lastMessageSentForRetry);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastMessageProcessedOnRetry)) {
        this.lastMessageProcessedOnRetry = data().deepCopy(fields()[2].schema(), other.lastMessageProcessedOnRetry);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ItemRetryTracker instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zabeer.kafkastreaming.model.ItemRetryTracker other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastMessageSentForRetry)) {
        this.lastMessageSentForRetry = data().deepCopy(fields()[1].schema(), other.lastMessageSentForRetry);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastMessageProcessedOnRetry)) {
        this.lastMessageProcessedOnRetry = data().deepCopy(fields()[2].schema(), other.lastMessageProcessedOnRetry);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastMessageSentForRetry' field.
      * @return The value.
      */
    public long getLastMessageSentForRetry() {
      return lastMessageSentForRetry;
    }


    /**
      * Sets the value of the 'lastMessageSentForRetry' field.
      * @param value The value of 'lastMessageSentForRetry'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder setLastMessageSentForRetry(long value) {
      validate(fields()[1], value);
      this.lastMessageSentForRetry = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastMessageSentForRetry' field has been set.
      * @return True if the 'lastMessageSentForRetry' field has been set, false otherwise.
      */
    public boolean hasLastMessageSentForRetry() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastMessageSentForRetry' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder clearLastMessageSentForRetry() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastMessageProcessedOnRetry' field.
      * @return The value.
      */
    public long getLastMessageProcessedOnRetry() {
      return lastMessageProcessedOnRetry;
    }


    /**
      * Sets the value of the 'lastMessageProcessedOnRetry' field.
      * @param value The value of 'lastMessageProcessedOnRetry'.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder setLastMessageProcessedOnRetry(long value) {
      validate(fields()[2], value);
      this.lastMessageProcessedOnRetry = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastMessageProcessedOnRetry' field has been set.
      * @return True if the 'lastMessageProcessedOnRetry' field has been set, false otherwise.
      */
    public boolean hasLastMessageProcessedOnRetry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastMessageProcessedOnRetry' field.
      * @return This builder.
      */
    public com.zabeer.kafkastreaming.model.ItemRetryTracker.Builder clearLastMessageProcessedOnRetry() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemRetryTracker build() {
      try {
        ItemRetryTracker record = new ItemRetryTracker();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastMessageSentForRetry = fieldSetFlags()[1] ? this.lastMessageSentForRetry : (java.lang.Long) defaultValue(fields()[1]);
        record.lastMessageProcessedOnRetry = fieldSetFlags()[2] ? this.lastMessageProcessedOnRetry : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemRetryTracker>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemRetryTracker>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemRetryTracker>
    READER$ = (org.apache.avro.io.DatumReader<ItemRetryTracker>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeLong(this.lastMessageSentForRetry);

    out.writeLong(this.lastMessageProcessedOnRetry);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.lastMessageSentForRetry = in.readLong();

      this.lastMessageProcessedOnRetry = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.lastMessageSentForRetry = in.readLong();
          break;

        case 2:
          this.lastMessageProcessedOnRetry = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










